import Head from "next/head";
import { TechData } from "../ui/Data";

export default function Home() {
    return (
        <>
            <Head>
                <title>Personal Page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className="cover">
                    <img
                        id="profile"
                        alt="profile"
                        src="https://avatars.githubusercontent.com/u/50919263?v=4"
                    />
                </div>
                <div className="profile-container">
                    <div id="bio">
                        <div>
                            <h2 id="name">Yesu Babu .G</h2>
                        </div>
                        <h3>age:22</h3>
                        <h5>(fresher Developer)</h5>
                        <div>"|------ information ------|"</div>
                    </div>
                </div>
                <div className="card-outercontainer">
                    <div className="card-innercontainer">
                        {TechData.map((card) => (
                            <div key={TechData.id} className={card.id}>
                                {card.data}
                            </div>
                        ))}
                    </div>
                </div>
            </main>
        </>
    );
}
