import Head from "next/head";
import Profile from "../ui/Profile";
import Contact from "../ui/Contact";
import Card from "../ui/Card";

export default function Home() {
    return (
        <>
            <Head>
                <title id="title">Personal site</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Profile />
                <Card />
                <Contact />
                <div className="footer"></div>
            </main>
        </>
    );
}
